<?php

/**
 * @file
 * Install, update and uninstall functions for module.
 */

/**
 * Implements hook_uninstall().
 */
function apiproduct_access_extended_uninstall() {
  // Remove all variables.
  $variable_name_prefix = apiproduct_access_extended_modulename() . '_';
  $result = db_select('variable', 'v')
    ->fields('v', array('name'))
    ->condition('name', db_like($variable_name_prefix) . '%', 'LIKE')
    ->execute();
  foreach ($result as $row) {
    variable_del($row->name);
  }
}
